---
title: "Project"
author: "Aksheytha"
date: "2022-12-04"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#remove.packages("rlang")
#install.packages("rlang")

library(tidyverse)
library(dplyr)
dat <- read.csv("C:\\Users\\akshe\\Downloads\\brown_universal.csv")



nounframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "NOUN")

noun <- proportions(table(nounframe$word))


verbframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "VERB") 

verb <- proportions(table(verbframe$word))

proframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "PRON") 

pro <- proportions(table(proframe$word))

advframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "ADV") 

adv <- proportions(table(advframe$word))

conjframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "CONJ") 

conj <- proportions(table(conjframe$word))

.frame <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == ".") 

. <- proportions(table(.frame$word))

adpframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "ADP") 

adp <- proportions(table(adpframe$word))

detframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "DET") 

det <- proportions(table(detframe$word))

prtframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "PRT") 

prt <- proportions(table(prtframe$word))


adjframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "ADJ") 

adj <- proportions(table(adjframe$word))

numframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "NUM") 

num <- proportions(table(numframe$word))


xframe <- dat %>%
  mutate(word = factor(word)) %>%
  group_by(word) %>%
  filter(pos == "X") 

x <- proportions(table(xframe$word))


varDat <- dat %>%
  filter(pos == "X") %>%
  count(word) %>%
  mutate(unique = n==1) %>%
  pull(unique) %>%
  sum()



var2Dat <- dat %>%
  filter(pos == "X")




#c(0,4590/83721,55/144766, 907/56239,4/38151,23/137019, 15702/275558, 910/14874,27/49334, 222/29829,4504/182750, 703/1386)


#new <- proportions(table(newWord$word))
#new

#bind<- rbind(noun, verb, pro, adv, conj, ., adp, det, prt, adj, num, x)

#Add a column that has the number of adj, verb, that only appear once


bind<- rbind(.,adj,adp,adv,conj,det,noun,num,pro,prt,verb,x)

#changedBind <- cbind(bind, c(0,4590/83721,55/144766, 907/56239,4/38151,23/137019, 15702/275558, 910/14874,27/49334, 222/29829,4504/182750, 703/1386))

#changedBind[,56058]
#dim(changedBind)




#bind[,2] #Emission prob



tp <- proportions(table(dat$pos[-1000000], dat$pos[-1]), margin = 1) #Transition prob



dd<- dat %>% 
  group_by(sentence) %>%
  group_modify(~ add_row(.x, .before = 0)) %>%
  ungroup() #%>%
  #mutate(pos = ifelse(is.na(pos), "BOS", pos)) 



d. <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == ".") 



dadj <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "ADJ") 


dadp <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "ADP") 


dadv <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "ADV") 


dconj<- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "CONJ") 

ddet<- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "DET") 

dnoun <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "NOUN") 

dnum <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "NUM") 

dpron <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "PRON") 


dprt <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "PRT") 

dverb <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "VERB") 

dx <- dd %>%
  group_by(sentence)%>%
  slice_head(n = 2) %>%
  filter(pos == "X") 




#aggregate(dd$pos, by = list(dd$sentence), FUN = first)


library(HMM)

my_hmm <- initHMM(States = c(".", "ADJ", "ADP", "ADV", "CONJ", "DET", "NOUN", "NUM", "PRON", "PRT", "VERB", "X"),
                  Symbols = unique(sort(dat$word)), #Symbols = c(......, "newword")
                  startProbs = c(.0889,.0343,.123,.0913,.049,.213,.141,.017,.160,.037,.045,.0005),
                  transProbs = tp,
                  emissionProbs = bind)

viterbi(my_hmm, as.character(dat$word[1:16]))



#For each sentence, remove sentence from data set. For each part of speech, what percentage of words in the sentence would be new
#Very similar to counting number of each part of speech that only appears once








```


```{r}
train <- sort(sample(57343, .9 * 57343))
test <- setdiff(1:57343, train)
test <- dat %>%
  filter(sentence %in% test)

train <- dat %>% 
  filter(sentence %in% train)





changedBind <- cbind(bind, c(0,4590/83721,55/144766, 907/56239,4/38151,23/137019, 15702/275558, 910/14874,27/49334, 222/29829,4504/182750, 703/1386))

#changedBind[,56058]



tp <- proportions(table(dat$pos[-1000000], dat$pos[-1]), margin = 1) #Transition prob



my_hmm2 <- initHMM(States = c(".", "ADJ", "ADP", "ADV", "CONJ", "DET", "NOUN", "NUM", "PRON", "PRT", "VERB", "X"),
                  Symbols = c(unique(sort(dat$word)), "newWord"), #Symbols = c(......, "newWord")
                  startProbs = c(.0889,.0343,.123,.0913,.049,.213,.141,.017,.160,.037,.045,.0005),
                  transProbs = tp,
                  emissionProbs = changedBind)

viterbi(my_hmm2, as.character(test$word[444:446]))

```


